server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://database-healthcare.czqr06altblj.us-east-2.rds.amazonaws.com:3306/HealthCareSystem
    username: admin
    password: Dunghoi1
jpa:
  hibernate:
    naming:
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

jwt.secret: company